### ISSUE TITLE
Breaking changes appeared after upgrading typescript version from ~3.5.3 to ~3.7.5

### ISSUE THREAD

**Issue by sh4444dow** [sweetalert2/ngx-sweetalert2#149]
In commit https://github.com/sweetalert2/ngx-sweetalert2/commit/093a1f0595f2264f9625d7d9f8c94e22ea9062c0, you upgraded typescript version to support Angular 9. This is honorable :)

Unfortunately, all applications pointing to previous version of angular (e.g.. `8.2.14`) and defining `@sweetalert2/ngx-sweetalert2` with version `^7.3.0` will logically points to `7.4.0` version of `@sweetalert2/ngx-sweetalert2` (because of `^`) and triggers terrible compilation errors on `ng build --prod` :
```
ERROR in ../node_modules/@sweetalert2/ngx-sweetalert2/lib/sweetalert2-loader.service.d.ts:9:9 - error TS1086: An accessor cannot be declared in an ambient context.

9     get swal(): Promise<typeof SwalDefault>;
          ~~~~
../node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts:101:9 - error TS1086: An accessor cannot be declared in an ambient context.

101     set swalOptions(options: SweetAlertOptions);
            ~~~~~~~~~~~
../node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts:107:9 - error TS1086: An accessor cannot be declared in an ambient context.

107     get swalOptions(): SweetAlertOptions;
            ~~~~~~~~~~~
../node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts:121:9 - error TS1086: An accessor cannot be declared in an ambient context.

121     set swalVisible(visible: boolean);
            ~~~~~~~~~~~
../node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts:122:9 - error TS1086: An accessor cannot be declared in an ambient context.

122     get swalVisible(): boolean;
            ~~~~~~~~~~~
../node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.directive.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27     set swal(options: SwalComponent | SweetAlertOptions | SweetAlertArrayOptions);
```

I strongly recommend to you to advice users to reference `~7.3.0` instead of `^7.3.0` or consider to directly upgrade `@sweetalert2/ngx-sweetalert2` to `8.0.0` to include angular 9 support 👍

**Comment by toverux** [comment]
Ah... I knew about accessors support in ambient context, but that, was hard to anticipate.
Very sorry for the inconvenience.

I'm thinking about downlevelling the .d.ts (found this : https://github.com/sandersn/downlevel-dts) to continue supporting Angular 8 users though, I think it would be sad to just leave them with the current version forever.

In the meantime... I usually stick with the recommended version of TypeScript for Angular, but couln't wait for 3.7 on Angular 8 because of the new optional navigation operator and more.
On a large codebase, I used TypeScript 3.7 on Angular 8 for a while without problem with just this line added to `polyfills.ts`:

```ts
// @todo ng-9 Remove this https://github.com/angular/angular-cli/issues/16071
// @ts-ignore
window.__importDefault = mod => mod?.__esModule ? mod : { default: mod };
```

Just in case you'd also like to benefit from the newest language features without upgrading Angular yet.

Thanks for the heads up!

**Comment by toverux** [comment]
Sorry, version 7.4.1 is also broken, but in another way.
I've implemented .d.ts downlevelling and used package.json's `typesVersions` (Angular 8 was using an alternative version of the .d.ts files, Angular 9 used the current ones), and it worked very well for Angular 8... except in AoT where it was failing in a strange way.

I have no other choice than to drop Angular 8 support from here and release a new major.

Angular 8 users should stay on `~7.3.0`. All three versions in range `~7.4.0` are broken and should be avoided, and have been removed from GitHub and deprecated on npm.

**Comment by sh4444dow** [comment]
Hello @toverux, I'm sorry to hear that downlevelling did not solve issue from all points of view :/ 
Thank you for you hard work and your reactivity about creating a new **major** version of 
🎉`ngx-sweetalert2`🎉 for supporting Angular 9 :)

**Comment by sandersn** [comment]
@toverux I am the author of downlevel-dts and I am aware that it is not ready for wide use. What problems did you run into specifically? I'd like to see whether I can fix them.

**Comment by toverux** [comment]
Hi, thank you very much for proposing your help!
Honestly downlevel-dts did a great job, there wasn't any problem in the generated files, that, I can guarantee.

It worked with Angular in JiT, since typings were fine. But there was a problem in AoT, seemingly coming from the AoT metadata file that was corrupt. Somehow that file appeared to be connected to the .d.ts files and that, didn't work. Probably. I didn't investigate to much as the error was pretty cryptic and had no serious lead to fix the problem.

Another possibility could've been to replace entirely the original .d.ts files and try with that.

If you have some knowledge of Angular material I could try to replicate what I did (discarded my work on this since then).

**Comment by sandersn** [comment]
No, unfortunately I know very little about angular. =(
