### ISSUE TITLE
Confirm by Enter key does not work in modal window

### ISSUE THREAD

**Issue by PavelValentov** [sweetalert2/ngx-sweetalert2#62]
I call JQuery modal, which running with parameter {keyboard: false}

```
    $('#cardModal').modal({
      backdrop: 'static',
      keyboard: false
    });
```

After that I call "swall2" with parameters {allowEnterKey: true, allowEscapeKey: true}

Press Escape — swal closing, retuning to the previous modal.
Press Enter — no actions from swall (promise did not triggered).

This code called from the normal window works well.

```
    swal({
      title: 'Discard changes?',
      text: 'confirm discard changes',
      type: 'question',
      target: 'body',
      allowEnterKey: true,
      allowEscapeKey: true,
      showCancelButton: true,
      focusConfirm: true,
      confirmButtonClass: 'btn btn-success',
      cancelButtonClass: 'btn btn-danger',
      confirmButtonText: 'Yes, dismiss',
      cancelButtonText: 'Continue edition',
      buttonsStyling: false
    })
      .then((x) => {
        console.log('SWAL:', x);
        return (x && x.value === true);
      })
      .catch( (err) => {
        console.log('ERROR SWAL:', err);
        // swal.noop;
        return false;
      });
```

In the case I have to subscribe for window's keypress events and execute '13' and '27' keys to call not documented functions "clickCancel" and "clickConfirm":
```
    if (event.keyCode === 27) {
      if (this.shared.execSwalKeys) {
        swal.clickCancel();
      }
    }
    if (event.keyCode === 13) {
      if (this.shared.execSwalKeys) {
        swal.clickConfirm();
      }
    }

```

(Google Crhome 65.0.3325.181, Angular 5)

**Comment by toverux** [comment]
This is most likely a SweetAlert2 issue. This integration does not perform DOM operations and the returned promise is the one given by SweetAlert2.

**Comment by limonte** [comment]
@PavelValentov the issue should be fixed in the latest SweetAlert2 release.

**Comment by Pasandil** [comment]
@limonte  is this issue fixed.?
This is 2019 and i am still having the issue.

**Comment by limonte** [comment]
Yup, this is 2019 and this issue is fixed.

If you're still experiencing it, please report here: https://github.com/sweetalert2/sweetalert2/issues/new/
